# ============================================================
# Project Phantom - Phase 6: Timing Side-Channel + Test Suite
# Author: Proma Roy
# Course: CSC I0420 - Secure Operating Systems
#
# Phase 6A: Timing side-channel analysis
#           Detects ETW tampering through scheduler jitter
#           Inspired by Chronos v2 timing attack concepts
#
# Phase 6B: Automated test suite
#           Validates all project phases using real data
#
# NOTE: This file is a standalone addition to the project.
#       Existing files (etw_baseline_monitor.py,
#       etw_correlator.py) are NOT modified.
#
# Usage:
#   python etw_phase6.py              # run full Phase 6 analysis
#   python etw_phase6.py --test       # run test suite only
#   python etw_phase6.py --timing     # run timing analysis only
#   python etw_phase6.py --all        # run everything
# ============================================================

import json
import os
import sys
import datetime
import statistics
import time

# ── Configuration ─────────────────────────────────────────────
# input files — same files generated by Phase 2 and Phase 3
BASELINE_FILE  = "etw_baseline_log.json"
TAMPERED_FILE  = "etw_tampered_log.json"
ALERT_FILE     = "siem_alert.json"
REPORT_FILE    = "phantom_analysis_report.txt"

# output files — new files created by Phase 6
TIMING_REPORT  = "phantom_timing_report.txt"
TEST_REPORT    = "phantom_test_report.txt"
PHASE6_REPORT  = "phantom_phase6_full_report.txt"

# timing anomaly threshold
# if standard deviation of intervals exceeds this we flag an anomaly
TIMING_ANOMALY_THRESHOLD = 0.5  # seconds

# ── Helper: get current timestamp ────────────────────────────
def get_timestamp():
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")

# ── Helper: load JSON log ─────────────────────────────────────
def load_log(filename):
    if not os.path.exists(filename):
        return None
    with open(filename, 'r') as f:
        return json.load(f)

# ── Helper: print section header ─────────────────────────────
def print_header(title):
    print()
    print("=" * 60)
    print(f"  {title}")
    print("=" * 60)

# ── Helper: print sub-header ─────────────────────────────────
def print_subheader(title):
    print()
    print(f"── {title} " + "─" * (56 - len(title)))

# ============================================================
# PHASE 6A: TIMING SIDE-CHANNEL ANALYSIS
# ============================================================

def analyze_timing_sidechannel(samples, label):
    """
    Analyzes sample timestamps to detect scheduler jitter.

    Theory (Chronos v2 connection):
    When ETW is healthy the kernel processes events normally
    and our Python sampler runs at consistent 2-second intervals.

    When EtwEventWrite is patched the kernel encounters the
    patched RET instruction and has to handle the unexpected
    return differently. This creates measurable scheduling
    irregularities that show up as jitter in our timestamps.

    This is a user-space observable timing side-channel —
    we detect kernel-level tampering without kernel access.
    Directly inspired by Chronos v2 scheduler timing attacks.
    """
    if len(samples) < 3:
        print(f"  [-] Not enough samples for timing analysis: {len(samples)}")
        return None

    # extract timestamps from each sample
    timestamps = []
    for s in samples:
        try:
            ts = datetime.datetime.strptime(
                s['timestamp'],
                "%Y-%m-%d %H:%M:%S.%f")
            timestamps.append(ts)
        except (ValueError, KeyError):
            continue

    if len(timestamps) < 3:
        print(f"  [-] Could not parse timestamps")
        return None

    # calculate intervals between consecutive samples
    # these should all be approximately 2.0 seconds
    intervals = []
    for i in range(1, len(timestamps)):
        delta = (timestamps[i] - timestamps[i-1]).total_seconds()
        intervals.append(delta)

    # statistical analysis of intervals
    avg_interval   = statistics.mean(intervals)
    stdev_interval = statistics.stdev(intervals)
    min_interval   = min(intervals)
    max_interval   = max(intervals)
    max_jitter     = max_interval - min_interval
    median_interval = statistics.median(intervals)

    # detect anomaly — high stdev means irregular scheduling
    timing_anomaly = stdev_interval > TIMING_ANOMALY_THRESHOLD

    # calculate coefficient of variation (CV)
    # CV = stdev/mean — normalized measure of variability
    # higher CV during tampering suggests kernel interference
    cv = (stdev_interval / avg_interval) * 100 if avg_interval > 0 else 0

    result = {
        "label"             : label,
        "sample_count"      : len(intervals),
        "avg_interval_sec"  : round(avg_interval, 4),
        "median_interval_sec": round(median_interval, 4),
        "stdev_interval_sec": round(stdev_interval, 4),
        "min_interval_sec"  : round(min_interval, 4),
        "max_interval_sec"  : round(max_interval, 4),
        "max_jitter_sec"    : round(max_jitter, 4),
        "coeff_variation_pct": round(cv, 2),
        "timing_anomaly"    : timing_anomaly,
        "all_intervals"     : [round(x, 4) for x in intervals]
    }

    # print results
    print_subheader(f"Timing Analysis: {label}")
    print(f"  Samples analyzed         : {len(intervals)}")
    print(f"  Expected interval        : 2.0000 sec")
    print(f"  Average interval         : {avg_interval:.4f} sec")
    print(f"  Median interval          : {median_interval:.4f} sec")
    print(f"  Std deviation            : {stdev_interval:.4f} sec")
    print(f"  Min interval             : {min_interval:.4f} sec")
    print(f"  Max interval             : {max_interval:.4f} sec")
    print(f"  Max jitter               : {max_jitter:.4f} sec")
    print(f"  Coefficient of variation : {cv:.2f}%")
    print()

    if timing_anomaly:
        print(f"  [!] TIMING ANOMALY DETECTED")
        print(f"  [!] Stdev {stdev_interval:.4f} exceeds threshold {TIMING_ANOMALY_THRESHOLD}")
        print(f"  [!] Irregular kernel scheduling detected")
    else:
        print(f"  [+] No timing anomaly — scheduling is consistent")

    return result


def run_timing_analysis():
    """
    Main Phase 6A function.
    Runs timing side-channel analysis on both baseline
    and tampered logs and compares the results.
    """
    print_header("PHASE 6A: TIMING SIDE-CHANNEL ANALYSIS")
    print("  Connecting Chronos v2 concepts to Project Phantom")
    print("  Detecting ETW tampering through scheduler jitter")

    # load both logs
    baseline = load_log(BASELINE_FILE)
    tampered = load_log(TAMPERED_FILE)

    if not baseline:
        print(f"\n  [-] Baseline log not found: {BASELINE_FILE}")
        print("  [-] Run Phase 2 first to generate baseline data")
        return None

    if not tampered:
        print(f"\n  [-] Tampered log not found: {TAMPERED_FILE}")
        print("  [-] Run Phase 3 + Phase 2 to generate tampered data")
        return None

    # analyze both logs
    b_timing = analyze_timing_sidechannel(
        baseline.get('samples', []),
        "BASELINE (Normal ETW)")

    t_timing = analyze_timing_sidechannel(
        tampered.get('samples', []),
        "TAMPERED (ETW Blinded)")

    if not b_timing or not t_timing:
        return None

    # compare the two timing profiles
    print_subheader("Timing Comparison: Baseline vs Tampered")

    stdev_diff  = t_timing['stdev_interval_sec'] - b_timing['stdev_interval_sec']
    jitter_diff = t_timing['max_jitter_sec'] - b_timing['max_jitter_sec']
    cv_diff     = t_timing['coeff_variation_pct'] - b_timing['coeff_variation_pct']
    avg_diff    = t_timing['avg_interval_sec'] - b_timing['avg_interval_sec']

    print(f"  {'Metric':<30} {'Baseline':>12} {'Tampered':>12} {'Delta':>12}")
    print(f"  {'-'*30} {'-'*12} {'-'*12} {'-'*12}")
    print(f"  {'Avg interval (sec)':<30} {b_timing['avg_interval_sec']:>12.4f} {t_timing['avg_interval_sec']:>12.4f} {avg_diff:>+12.4f}")
    print(f"  {'Std deviation (sec)':<30} {b_timing['stdev_interval_sec']:>12.4f} {t_timing['stdev_interval_sec']:>12.4f} {stdev_diff:>+12.4f}")
    print(f"  {'Max jitter (sec)':<30} {b_timing['max_jitter_sec']:>12.4f} {t_timing['max_jitter_sec']:>12.4f} {jitter_diff:>+12.4f}")
    print(f"  {'Coeff variation (%)':<30} {b_timing['coeff_variation_pct']:>12.2f} {t_timing['coeff_variation_pct']:>12.2f} {cv_diff:>+12.2f}")

    print()

    # verdict
    print_subheader("Timing Side-Channel Verdict")

    timing_detection = (
        abs(stdev_diff) > 0.01 or
        abs(jitter_diff) > 0.1 or
        abs(cv_diff) > 1.0
    )

    if timing_detection:
        print("  [!] TIMING SIDE-CHANNEL DETECTED")
        print(f"  [!] Scheduler behavior differs between baseline and tampered")
        print(f"  [!] Stdev delta: {stdev_diff:+.4f} sec")
        print(f"  [!] Jitter delta: {jitter_diff:+.4f} sec")
        print(f"  [!] CV delta: {cv_diff:+.2f}%")
        print()
        print("  Research significance:")
        print("  Timing differences are observable from user-mode Python")
        print("  without any kernel privileges or ETW access.")
        print("  This demonstrates a passive side-channel detection method")
        print("  inspired by Chronos v2 scheduler timing attack concepts.")
    else:
        print("  [*] No significant timing side-channel detected")
        print("  [*] Kernel scheduling remained consistent during tampering")
        print("  [*] This is also a valid finding — documents OS resilience")
        print("  [*] ETW-TI protections may have limited kernel-level impact")

    print()

    # save timing report
    report_lines = [
        "=" * 60,
        "  PROJECT PHANTOM - TIMING SIDE-CHANNEL REPORT",
        "  Phase 6A: Chronos v2 Integration",
        f"  Generated: {get_timestamp()}",
        "=" * 60,
        "",
        "THEORY:",
        "  When EtwEventWrite is patched with RET (0xC3), the kernel",
        "  handles the unexpected early return differently, creating",
        "  measurable scheduling irregularities observable from",
        "  user-space timing measurements — a passive side-channel.",
        "",
        "BASELINE TIMING:",
        f"  Avg interval    : {b_timing['avg_interval_sec']} sec",
        f"  Std deviation   : {b_timing['stdev_interval_sec']} sec",
        f"  Max jitter      : {b_timing['max_jitter_sec']} sec",
        f"  Coeff variation : {b_timing['coeff_variation_pct']}%",
        f"  Anomaly         : {b_timing['timing_anomaly']}",
        "",
        "TAMPERED TIMING:",
        f"  Avg interval    : {t_timing['avg_interval_sec']} sec",
        f"  Std deviation   : {t_timing['stdev_interval_sec']} sec",
        f"  Max jitter      : {t_timing['max_jitter_sec']} sec",
        f"  Coeff variation : {t_timing['coeff_variation_pct']}%",
        f"  Anomaly         : {t_timing['timing_anomaly']}",
        "",
        "COMPARISON:",
        f"  Stdev delta     : {stdev_diff:+.4f} sec",
        f"  Jitter delta    : {jitter_diff:+.4f} sec",
        f"  CV delta        : {cv_diff:+.2f}%",
        f"  Detection       : {'YES' if timing_detection else 'NO'}",
        "",
        "CONCLUSION:",
        "  Timing side-channel analysis provides a passive,",
        "  kernel-privilege-free detection method that complements",
        "  the cross-correlation approach in Phase 5.",
        "  Inspired by Chronos v2 scheduler timing attack concepts.",
        "=" * 60
    ]

    with open(TIMING_REPORT, 'w') as f:
        f.write("\n".join(report_lines))
    print(f"  [+] Timing report saved to: {TIMING_REPORT}")

    return {
        "baseline_timing"   : b_timing,
        "tampered_timing"   : t_timing,
        "stdev_delta"       : stdev_diff,
        "jitter_delta"      : jitter_diff,
        "cv_delta"          : cv_diff,
        "timing_detected"   : timing_detection
    }


# ============================================================
# PHASE 6B: AUTOMATED TEST SUITE
# ============================================================

def run_test_suite():
    """
    Automated test suite validating all project phases.
    Uses real data files — never hardcoded values.
    Run with: python etw_phase6.py --test
    """
    print_header("PHASE 6B: AUTOMATED TEST SUITE")
    print("  Validating all project phases using real data")
    print("  All tests use actual JSON files — no hardcoded values")

    tests_passed = 0
    tests_failed = 0
    test_results = []

    def run_test(test_number, description, test_func):
        nonlocal tests_passed, tests_failed
        print(f"\n  [TEST {test_number}] {description}")
        try:
            result = test_func()
            if result['passed']:
                print(f"  PASS — {result['message']}")
                tests_passed += 1
            else:
                print(f"  FAIL — {result['message']}")
                tests_failed += 1
            test_results.append({
                "test"    : test_number,
                "desc"    : description,
                "passed"  : result['passed'],
                "message" : result['message']
            })
        except Exception as e:
            print(f"  ERROR — {str(e)}")
            tests_failed += 1
            test_results.append({
                "test"    : test_number,
                "desc"    : description,
                "passed"  : False,
                "message" : f"Exception: {str(e)}"
            })

    # ── Test 1: Baseline log exists and has valid structure ───
    def test_baseline_exists():
        baseline = load_log(BASELINE_FILE)
        if not baseline:
            return {"passed": False, "message": f"{BASELINE_FILE} not found"}
        samples = baseline.get('samples', [])
        if len(samples) == 0:
            return {"passed": False, "message": "No samples in baseline log"}
        if 'start_time' not in baseline:
            return {"passed": False, "message": "Missing start_time field"}
        return {"passed": True, "message": f"{len(samples)} samples found in baseline"}

    run_test(1, "Baseline log exists and has valid structure", test_baseline_exists)

    # ── Test 2: Tampered log exists and has valid structure ───
    def test_tampered_exists():
        tampered = load_log(TAMPERED_FILE)
        if not tampered:
            return {"passed": False, "message": f"{TAMPERED_FILE} not found"}
        samples = tampered.get('samples', [])
        if len(samples) == 0:
            return {"passed": False, "message": "No samples in tampered log"}
        return {"passed": True, "message": f"{len(samples)} samples found in tampered log"}

    run_test(2, "Tampered log exists and has valid structure", test_tampered_exists)

    # ── Test 3: Process counts are realistic ─────────────────
    def test_process_count_realistic():
        baseline = load_log(BASELINE_FILE)
        if not baseline:
            return {"passed": False, "message": "Baseline log not available"}
        counts = [s['process_count'] for s in baseline['samples']]
        avg = statistics.mean(counts)
        if not (100 < avg < 1000):
            return {"passed": False, "message": f"Avg process count {avg:.1f} is unrealistic"}
        return {"passed": True, "message": f"Avg process count {avg:.1f} is realistic (100-1000 range)"}

    run_test(3, "Process counts are realistic", test_process_count_realistic)

    # ── Test 4: ETW provider was active during baseline ──────
    def test_etw_active():
        baseline = load_log(BASELINE_FILE)
        if not baseline:
            return {"passed": False, "message": "Baseline log not available"}
        etw_active = baseline.get('etw_active', False)
        provider   = baseline.get('provider', 'unknown')
        if not etw_active:
            return {"passed": False, "message": f"ETW was not active — provider: {provider}"}
        return {"passed": True, "message": f"ETW was active — provider: {provider}"}

    run_test(4, "ETW provider was active during baseline capture", test_etw_active)

    # ── Test 5: CPU values are in valid range ─────────────────
    def test_cpu_valid():
        baseline = load_log(BASELINE_FILE)
        if not baseline:
            return {"passed": False, "message": "Baseline log not available"}
        cpu_values = [s['cpu_percent'] for s in baseline['samples']]
        for v in cpu_values:
            if not (0 <= v <= 100):
                return {"passed": False, "message": f"Invalid CPU value: {v}%"}
        avg_cpu = statistics.mean(cpu_values)
        return {"passed": True, "message": f"All CPU values valid — avg: {avg_cpu:.1f}%"}

    run_test(5, "CPU usage values are in valid range (0-100%)", test_cpu_valid)

    # ── Test 6: Memory values are in valid range ──────────────
    def test_memory_valid():
        baseline = load_log(BASELINE_FILE)
        if not baseline:
            return {"passed": False, "message": "Baseline log not available"}
        mem_values = [s['memory_percent'] for s in baseline['samples']]
        for v in mem_values:
            if not (0 <= v <= 100):
                return {"passed": False, "message": f"Invalid memory value: {v}%"}
        avg_mem = statistics.mean(mem_values)
        return {"passed": True, "message": f"All memory values valid — avg: {avg_mem:.1f}%"}

    run_test(6, "Memory usage values are in valid range (0-100%)", test_memory_valid)

    # ── Test 7: Both logs have same sample structure ──────────
    def test_matching_structure():
        baseline = load_log(BASELINE_FILE)
        tampered = load_log(TAMPERED_FILE)
        if not baseline or not tampered:
            return {"passed": False, "message": "One or both logs not available"}
        b_keys = set(baseline['samples'][0].keys())
        t_keys = set(tampered['samples'][0].keys())
        if b_keys != t_keys:
            missing = b_keys - t_keys
            return {"passed": False, "message": f"Structure mismatch — missing keys: {missing}"}
        return {"passed": True, "message": f"Both logs have matching structure: {sorted(b_keys)}"}

    run_test(7, "Baseline and tampered logs have matching structure", test_matching_structure)

    # ── Test 8: Timestamps are valid and sequential ───────────
    def test_timestamps_valid():
        baseline = load_log(BASELINE_FILE)
        if not baseline:
            return {"passed": False, "message": "Baseline log not available"}
        timestamps = []
        for s in baseline['samples']:
            try:
                ts = datetime.datetime.strptime(
                    s['timestamp'], "%Y-%m-%d %H:%M:%S.%f")
                timestamps.append(ts)
            except ValueError as e:
                return {"passed": False, "message": f"Invalid timestamp: {e}"}
        # check they are sequential
        for i in range(1, len(timestamps)):
            if timestamps[i] <= timestamps[i-1]:
                return {"passed": False, "message": "Timestamps are not sequential"}
        return {"passed": True, "message": f"{len(timestamps)} timestamps are valid and sequential"}

    run_test(8, "All timestamps are valid and sequential", test_timestamps_valid)

    # ── Test 9: Detection gap calculation is valid ────────────
    def test_detection_gap_valid():
        baseline = load_log(BASELINE_FILE)
        tampered = load_log(TAMPERED_FILE)
        if not baseline or not tampered:
            return {"passed": False, "message": "One or both logs not available"}

        # extract process names from both
        b_names = set()
        for s in baseline['samples']:
            for p in s.get('processes', []):
                b_names.add(p['name'])

        t_names = set()
        for s in tampered['samples']:
            for p in s.get('processes', []):
                t_names.add(p['name'])

        missing = b_names - t_names
        gap_pct = round(len(missing) / max(len(b_names), 1) * 100, 2)

        if gap_pct < 0 or gap_pct > 100:
            return {"passed": False, "message": f"Detection gap {gap_pct}% is out of range"}
        return {"passed": True,
                "message": f"Detection gap: {gap_pct}% — {len(missing)} processes missing"}

    run_test(9, "Detection gap calculation produces valid result", test_detection_gap_valid)

    # ── Test 10: SIEM alert has required fields ───────────────
    def test_siem_alert_valid():
        if not os.path.exists(ALERT_FILE):
            return {"passed": True,
                    "message": "No SIEM alert file — no tampering detected (acceptable result)"}
        with open(ALERT_FILE) as f:
            alert = json.load(f)
        required = ['alert_id', 'severity', 'mitre_technique',
                   'mitre_tactic', 'ghost_processes', 'timestamp']
        missing = [k for k in required if k not in alert]
        if missing:
            return {"passed": False, "message": f"SIEM alert missing fields: {missing}"}
        ghost_count = len(alert['ghost_processes'])
        return {"passed": True,
                "message": f"SIEM alert valid — severity: {alert['severity']}, "
                          f"ghost processes: {ghost_count}"}

    run_test(10, "SIEM alert has all required fields", test_siem_alert_valid)

    # ── Test 11: Timing analysis produces valid intervals ─────
    def test_timing_intervals():
        baseline = load_log(BASELINE_FILE)
        if not baseline:
            return {"passed": False, "message": "Baseline log not available"}
        samples = baseline.get('samples', [])
        if len(samples) < 3:
            return {"passed": False, "message": f"Not enough samples: {len(samples)}"}
        timestamps = []
        for s in samples:
            try:
                ts = datetime.datetime.strptime(
                    s['timestamp'], "%Y-%m-%d %H:%M:%S.%f")
                timestamps.append(ts)
            except ValueError:
                continue
        intervals = [(timestamps[i] - timestamps[i-1]).total_seconds()
                     for i in range(1, len(timestamps))]
        avg = statistics.mean(intervals)
        # intervals should be approximately 2 seconds (1.5 to 3.5 is acceptable)
        if not (1.5 <= avg <= 3.5):
            return {"passed": False,
                    "message": f"Avg interval {avg:.4f}s outside expected range (1.5-3.5s)"}
        return {"passed": True,
                "message": f"Avg sampling interval: {avg:.4f}s (expected ~2.0s)"}

    run_test(11, "Sampling intervals are approximately 2 seconds", test_timing_intervals)

    # ── Test 12: Tampered log shows CPU anomaly ───────────────
    def test_cpu_anomaly():
        baseline = load_log(BASELINE_FILE)
        tampered = load_log(TAMPERED_FILE)
        if not baseline or not tampered:
            return {"passed": False, "message": "One or both logs not available"}
        b_cpu = statistics.mean([s['cpu_percent'] for s in baseline['samples']])
        t_cpu = statistics.mean([s['cpu_percent'] for s in tampered['samples']])
        delta = t_cpu - b_cpu
        # any difference is worth reporting — positive or negative
        return {"passed": True,
                "message": f"CPU during baseline: {b_cpu:.2f}% | "
                          f"tampered: {t_cpu:.2f}% | "
                          f"delta: {delta:+.2f}%"}

    run_test(12, "CPU anomaly comparison baseline vs tampered", test_cpu_anomaly)

    # ── Summary ───────────────────────────────────────────────
    print()
    print("=" * 60)
    print("  TEST SUITE RESULTS")
    print("=" * 60)
    print(f"  Tests passed : {tests_passed}")
    print(f"  Tests failed : {tests_failed}")
    print(f"  Total tests  : {tests_passed + tests_failed}")
    print()
    if tests_failed == 0:
        print("  ALL TESTS PASSED")
    else:
        print(f"  {tests_failed} TEST(S) FAILED — check output above")
    print("=" * 60)

    # save test report
    report_lines = [
        "=" * 60,
        "  PROJECT PHANTOM - AUTOMATED TEST SUITE REPORT",
        "  Phase 6B: Test Suite",
        f"  Generated: {get_timestamp()}",
        "=" * 60,
        ""
    ]
    for r in test_results:
        status = "PASS" if r['passed'] else "FAIL"
        report_lines.append(f"  [TEST {r['test']}] [{status}] {r['desc']}")
        report_lines.append(f"           {r['message']}")
        report_lines.append("")

    report_lines += [
        "=" * 60,
        f"  Tests passed : {tests_passed}",
        f"  Tests failed : {tests_failed}",
        f"  Total        : {tests_passed + tests_failed}",
        f"  Result       : {'ALL PASSED' if tests_failed == 0 else 'FAILURES DETECTED'}",
        "=" * 60
    ]

    with open(TEST_REPORT, 'w') as f:
        f.write("\n".join(report_lines))
    print(f"\n  [+] Test report saved to: {TEST_REPORT}")

    return tests_failed == 0


# ============================================================
# FULL PHASE 6 REPORT
# ============================================================

def generate_phase6_report(timing_results, test_passed):
    """Combines timing and test results into one Phase 6 report."""

    lines = [
        "=" * 60,
        "  PROJECT PHANTOM - PHASE 6 FULL REPORT",
        "  Timing Side-Channel + Test Suite",
        f"  Generated: {get_timestamp()}",
        "=" * 60,
        "",
        "PHASE 6A: TIMING SIDE-CHANNEL ANALYSIS",
        "─" * 60
    ]

    if timing_results:
        b = timing_results['baseline_timing']
        t = timing_results['tampered_timing']
        lines += [
            f"  Baseline avg interval   : {b['avg_interval_sec']} sec",
            f"  Tampered avg interval   : {t['avg_interval_sec']} sec",
            f"  Stdev delta             : {timing_results['stdev_delta']:+.4f} sec",
            f"  Jitter delta            : {timing_results['jitter_delta']:+.4f} sec",
            f"  CV delta                : {timing_results['cv_delta']:+.2f}%",
            f"  Timing anomaly detected : {timing_results['timing_detected']}",
            "",
            "  Chronos v2 connection:",
            "  This timing analysis applies scheduler side-channel",
            "  concepts to detect ETW tampering from user-space.",
            "  No kernel privileges required for detection."
        ]
    else:
        lines.append("  Timing analysis not available — check data files")

    lines += [
        "",
        "PHASE 6B: TEST SUITE",
        "─" * 60,
        f"  All tests passed        : {test_passed}",
        f"  Test report             : {TEST_REPORT}",
        "",
        "OUTPUT FILES",
        "─" * 60,
        f"  {TIMING_REPORT}",
        f"  {TEST_REPORT}",
        f"  {PHASE6_REPORT}",
        "",
        "=" * 60
    ]

    with open(PHASE6_REPORT, 'w') as f:
        f.write("\n".join(lines))
    print(f"\n  [+] Phase 6 full report saved to: {PHASE6_REPORT}")


# ============================================================
# ENTRY POINT
# ============================================================

def main():
    """Run full Phase 6 analysis."""
    print_header("PROJECT PHANTOM — PHASE 6")
    print("  Timing Side-Channel Analysis + Automated Test Suite")
    print(f"  Started: {get_timestamp()}")

    timing_results = run_timing_analysis()
    test_passed    = run_test_suite()

    generate_phase6_report(timing_results, test_passed)

    print()
    print_header("PHASE 6 COMPLETE")
    print("  Output files:")
    print(f"    {TIMING_REPORT}")
    print(f"    {TEST_REPORT}")
    print(f"    {PHASE6_REPORT}")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1] == "--test":
            run_test_suite()
        elif sys.argv[1] == "--timing":
            run_timing_analysis()
        elif sys.argv[1] == "--all":
            main()
        else:
            print(f"Unknown flag: {sys.argv[1]}")
            print("Usage:")
            print("  python etw_phase6.py           # full Phase 6")
            print("  python etw_phase6.py --test    # test suite only")
            print("  python etw_phase6.py --timing  # timing only")
            print("  python etw_phase6.py --all     # everything")
    else:
        main()